### ISSUE TITLE
Create Advanced Responsive Software Engineer Portfolio Website with Dark/Light Mode

### ISSUE THREAD

**Issue by Kumputaqkamayuq** [Kumputaqkamayuq/test#1]
## Project Overview
Create a modern, responsive software engineer portfolio website using vanilla HTML, JavaScript, and CSS. The website should showcase professional experience, projects, and skills while providing both dark and light mode themes for better user experience.

## Technical Requirements
- Have the About Div, Skills Div, Projects Div, and Contact Div inside a main div
- Make Hero Div the about me part of the page

### Core Technologies
- HTML5
- Vanilla JavaScript (No frameworks)
- CSS3 (with modern features like CSS Grid and Flexbox)

#### 1. Responsive Design
- Mobile-first approach
- Breakpoints for different screen sizes:
  - Mobile (< 768px)
  - Tablet (768px - 1024px)
  - Desktop (> 1024px)
- Fluid typography and spacing

#### 2. Theme Switching
- Dark/Light mode toggle button
- Persistent theme preference using localStorage
- Smooth transition animations between themes
- System preference detection (prefers-color-scheme)

#### 3. Layout Components
- Header
  - Navigation menu
  - Theme toggle
  - Responsive hamburger menu for mobile
- Hero Div
  - Professional photo
  - Name and title
  - Detailed professional background
  - Call-to-action buttons
- Skills Div
  - Skills showcase
  - Technologies expertise
- Projects Div
  - Project cards with:
    - Preview image
    - Title
    - Description
    - Technologies used
    - Live demo link
    - Source code link
- Experience Div
  - Timeline of work history
  - Education background
- Contact Div
  - Contact form
  - Social media links
  - Professional networks (GitHub, LinkedIn)
- Footer
  - Copyright information
  - Additional links

#### 4. Interactive Elements
- Smooth scroll behavior
- Hover effects on interactive elements
- Loading animations
- Project filtering capability
- Form validation

#### 5. Performance Optimization
- Lazy loading for images
- Minified CSS and JavaScript
- Optimized assets
- Semantic HTML for better SEO

#### CSS Architecture
```css
/* Example color variables structure */
:root {
  /* Light theme */
  --primary-light: #007bff;
  --background-light: #ffffff;
  --text-light: #333333;
  
  /* Dark theme */
  --primary-dark: #00a8ff;
  --background-dark: #1a1a1a;
  --text-dark: #ffffff;
}

[data-theme="dark"] {
  --primary: var(--primary-dark);
  --background: var(--background-dark);
  --text: var(--text-dark);
}

[data-theme="light"] {
  --primary: var(--primary-light);
  --background: var(--background-light);
  --text: var(text-light);
}
```

#### JavaScript Theme Switching
```javascript
// Theme switching logic example
const themeToggle = document.querySelector('#theme-toggle');
const prefersDarkScheme = window.matchMedia('(prefers-color-scheme: dark)');

function setTheme(theme) {
  document.documentElement.setAttribute('data-theme', theme);
  localStorage.setItem('theme', theme);
}

themeToggle.addEventListener('click', () => {
  const currentTheme = document.documentElement.getAttribute('data-theme');
  setTheme(currentTheme === 'dark' ? 'light' : 'dark');
});
```

### File Structure
```
portfolio/
├── index.html
├── css/
│   ├── style.css
│   ├── normalize.css
│   └── themes.css
├── js/
│   ├── main.js
│   ├── theme-switcher.js
│   └── animations.js
└── assets/
    ├── images/
    └── icons/
```

## Deliverables
1. Complete source code with proper documentation
2. Responsive design implementation across all major devices
3. Functional dark/light mode toggle with smooth transitions
4. Cross-browser compatibility (Chrome, Firefox, Safari, Edge)
5. Performance optimization report
6. Basic SEO implementation

## Acceptance Criteria
- [ ] Website is fully responsive across all major breakpoints
- [ ] Dark/Light mode toggle works and persists across sessions
- [ ] All interactive elements have appropriate hover/focus states
- [ ] Forms include proper validation and error handling
- [ ] Code is well-documented and follows best practices
- [ ] Website loads within 3 seconds on average connections
- [ ] Passes WCAG 2.1 AA accessibility standards
- [ ] Achieves 90+ score on Google Lighthouse for:
  - Performance
  - Accessibility
  - Best Practices
  - SEO

## Additional Notes
- Consider implementing progressive enhancement
- Use semantic HTML elements for better accessibility
- Implement proper meta tags for social sharing
- Add proper documentation for maintenance and future updates
